/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-02-12 18:18:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/E:/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FrontEndBaazarIndia/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1546417435312L));
    _jspx_dependants.put("/WEB-INF/views/Header.jsp", Long.valueOf(1549981407865L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html\">\r\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageinfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("Baazar India</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"#\">BAAZAR INDIA</a>\r\n");
      out.write("      \r\n");
      out.write(" </div>\r\n");
      out.write("  \r\n");
      out.write("    <ul class=\"nav navbar-nav\"> \r\n");
      out.write("      <li><a href=\"home\">HOME</a></li>\r\n");
      out.write("      <li><a href=\"login\">LOGIN</a></li>\r\n");
      out.write("      <li><a href=\"register\">REGISTER</a></li>\r\n");
      out.write("      <li><a href=\"contactus\">CONTACTUS</a></li>\r\n");
      out.write("      <li><a href=\"aboutus\">ABOUTUS</a></li>\r\n");
      out.write("      <li><a href=\"category\">MANAGE CATEGORY</a></li>\r\n");
      out.write("      <li><a href=\"product\">MANAGE PRODUCT</a></li>\r\n");
      out.write("      \r\n");
      out.write("     </ul>\r\n");
      out.write("     \r\n");
      out.write("     </div>\r\n");
      out.write("     \r\n");
      out.write("     </nav>\r\n");
      out.write("     <img src=\"E:\\Project\\image\\bootstrap_image.jpg\" width=\"1200\" height=\"300\">\r\n");
      out.write("     </body>\r\n");
      out.write("     </html>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"perform_login\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url(http://fonts.googleapis.com/css?family=Roboto:400);\r\n");
      out.write("body {\r\n");
      out.write("  background-color:#fff;\r\n");
      out.write("  -webkit-font-smoothing: antialiased;\r\n");
      out.write("  font: normal 14px Roboto,arial,sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".container {\r\n");
      out.write("    padding: 25px;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("}\r\n");
      out.write(".form-login {\r\n");
      out.write("    background-color: #EDEDED;\r\n");
      out.write("    padding-top: 10px;\r\n");
      out.write("    padding-bottom: 20px;\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("    padding-right: 20px;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    border-color:#d2d2d2;\r\n");
      out.write("    border-width: 5px;\r\n");
      out.write("    box-shadow:0 1px 0 #cfcfcf;\r\n");
      out.write("}\r\n");
      out.write("h4 { \r\n");
      out.write(" border:0 solid #fff; \r\n");
      out.write(" border-bottom-width:1px;\r\n");
      out.write(" padding-bottom:10px;\r\n");
      out.write(" text-align: center;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<script src=\"//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.1.min.js\">\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-offset-5 col-md-3\">\r\n");
      out.write("<div class=\"form-login\">\r\n");
      out.write("<h4>Welcome back.</h4>\r\n");
      out.write("<input type=\"text\" name=\"username\" required class=\"form-control input-sm chat-input\" placeholder=\"username\" />\r\n");
      out.write("</br>\r\n");
      out.write("<input type=\"password\" name=\"password\" required class=\"form-control input-sm chat-input\" placeholder=\"password\" />\r\n");
      out.write("</br>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("<span class=\"group-btn\">     \r\n");
      out.write(" <center> <input type=\"submit\" value=\"login\" class=\"btn btn-primary btn-md\"/></center>\r\n");
      out.write("\r\n");
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
